name: Release package on NPM

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.2]
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create ~/.npmrc file (for private packages)
        run: echo //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE }} >> ~/.npmrc |
          echo @warrenbrasil:registry=https://npm.pkg.github.com/ >> ~/.npmrc

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_PACKAGE }}
