name: Create release changelog

on:
  release:
    types: [published]

jobs:
  release-changelog:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build release changelog
        id: github_release
        uses: warrenbrasil/release-changelog-builder-action@v1
        with:
          configuration: '.github/configs/release-changelog.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release changelog
        uses: warrenbrasil/release-action@v1
        with:
          allowUpdates: true
          omitPrereleaseDuringUpdate: true
          body: ${{steps.github_release.outputs.changelog}}
          token: ${{ secrets.GITHUB_TOKEN }}
